[config]
schemaVersion = "0.0.1"

[package]
namespace = "mxpuffin"
name = "REPOShock"
versionNumber = "0.0.4"
description = "A mod for R.E.P.O that adds PiShock integration"
websiteUrl = "https://github.com/MxPuffin/REPOShock"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../LICENSE"
target = "/"

[[build.copy]]
source = "../bin/Release/netstandard2.1/REPOShock.dll"
target = "/BepInEx/plugins/mxpuffin-REPOShock/REPOShock.dll"

[[build.copy]]
source = "../bin/Release/netstandard2.1/PiShockClassLibrary.dll"
target = "/BepInEx/plugins/mxpuffin-REPOShock/PiShockClassLibrary.dll"

[publish]
repository = "https://github.com/MxPuffin/REPOShock"
communities = [ "repo", ]
[publish.categories]
repo = [ "misc", "mods", ]


